// Package store keeps saved graphs on disk: one JSON file per graph in a
// data directory, so graphs survive restarts and can be opened without the
// database.
//
// A saved graph is the schema at the moment of saving plus where each table
// was on screen, so it reopens exactly as it was left. It records which
// database it came from, but never the password.
package store

import (
	"cmp"
	"encoding/json"
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"slices"
	"strings"
	"time"

	"github.com/sanat-19/schema-lens/internal/schema"
)

// Graph is one saved graph.
type Graph struct {
	ID          string              `json:"id"`
	Name        string              `json:"name"`
	SavedAt     time.Time           `json:"savedAt"`
	Source      schema.Source       `json:"source"`
	Positions   map[string]Position `json:"positions,omitempty"` // table ID → centre on screen
	ShowColumns bool                `json:"showColumns"`
	Schema      *schema.Schema      `json:"schema"`
}

// Position is where a table sat on the graph.
type Position struct {
	X float64 `json:"x"`
	Y float64 `json:"y"`
}

// Summary is what the list of saved graphs shows, without the whole schema.
type Summary struct {
	ID       string        `json:"id"`
	Name     string        `json:"name"`
	SavedAt  time.Time     `json:"savedAt"`
	Source   schema.Source `json:"source"`
	Tables   int           `json:"tables"`
	Findings int           `json:"findings"`
}

// ErrNotFound means there is no saved graph with that ID.
var ErrNotFound = errors.New("saved graph not found")

// IDs are generated by Save, but they come back to us in URLs, so they are
// checked before use: nothing like "../../etc/passwd" gets near the disk.
var validID = regexp.MustCompile(`^[a-z0-9][a-z0-9-]{0,80}$`)

// Store is a directory of saved graphs.
type Store struct {
	dir string
}

// Open uses dir, creating it if needed. Only the current user can read it,
// since saved graphs describe your database.
func Open(dir string) (*Store, error) {
	if err := os.MkdirAll(dir, 0o700); err != nil {
		return nil, fmt.Errorf("creating graph directory: %w", err)
	}
	return &Store{dir: dir}, nil
}

// DefaultDir is ~/.config/schemalens/graphs on Linux, and the equivalent on
// macOS and Windows.
func DefaultDir() (string, error) {
	base, err := os.UserConfigDir()
	if err != nil {
		return "", err
	}
	return filepath.Join(base, "schemalens", "graphs"), nil
}

// Dir is where the graphs live, for telling the user.
func (s *Store) Dir() string { return s.dir }

// Save writes g as a new saved graph and returns its summary. The ID is made
// from the name and the time, e.g. "shop-before-migration-20260926-164210".
func (s *Store) Save(g Graph) (Summary, error) {
	if g.Schema == nil {
		return Summary{}, errors.New("nothing to save: no schema loaded")
	}
	g.Name = strings.TrimSpace(g.Name)
	if g.Name == "" {
		g.Name = g.Schema.Database
	}
	if g.SavedAt.IsZero() {
		g.SavedAt = time.Now().UTC()
	}
	g.ID = s.newID(g.Name, g.SavedAt)

	data, err := json.MarshalIndent(g, "", "  ")
	if err != nil {
		return Summary{}, err
	}
	if err := writeFileAtomic(s.path(g.ID), data); err != nil {
		return Summary{}, fmt.Errorf("saving graph: %w", err)
	}
	return summarize(&g), nil
}

// Get reads one saved graph.
func (s *Store) Get(id string) (*Graph, error) {
	if !validID.MatchString(id) {
		return nil, ErrNotFound
	}
	data, err := os.ReadFile(s.path(id))
	if errors.Is(err, os.ErrNotExist) {
		return nil, ErrNotFound
	}
	if err != nil {
		return nil, err
	}
	var g Graph
	if err := json.Unmarshal(data, &g); err != nil {
		return nil, fmt.Errorf("reading saved graph %s: %w", id, err)
	}
	if g.Schema == nil {
		return nil, fmt.Errorf("saved graph %s has no schema", id)
	}
	return &g, nil
}

// List returns every saved graph, newest first. A file that can't be read
// is skipped rather than hiding all the others.
func (s *Store) List() ([]Summary, error) {
	entries, err := os.ReadDir(s.dir)
	if err != nil {
		return nil, err
	}
	out := []Summary{}
	for _, e := range entries {
		id, ok := strings.CutSuffix(e.Name(), ".json")
		if !ok || e.IsDir() {
			continue
		}
		g, err := s.Get(id)
		if err != nil {
			continue
		}
		out = append(out, summarize(g))
	}
	slices.SortFunc(out, func(a, b Summary) int {
		return cmp.Or(b.SavedAt.Compare(a.SavedAt), cmp.Compare(a.ID, b.ID))
	})
	return out, nil
}

// Delete removes a saved graph.
func (s *Store) Delete(id string) error {
	if !validID.MatchString(id) {
		return ErrNotFound
	}
	err := os.Remove(s.path(id))
	if errors.Is(err, os.ErrNotExist) {
		return ErrNotFound
	}
	return err
}

func (s *Store) path(id string) string {
	return filepath.Join(s.dir, id+".json")
}

var notSlugChars = regexp.MustCompile(`[^a-z0-9]+`)

// newID makes a readable, unique file name from the graph's name.
func (s *Store) newID(name string, at time.Time) string {
	slug := strings.Trim(notSlugChars.ReplaceAllString(strings.ToLower(name), "-"), "-")
	if len(slug) > 40 {
		slug = strings.TrimRight(slug[:40], "-")
	}
	if slug == "" {
		slug = "graph"
	}
	base := slug + "-" + at.Format("20060102-150405")
	id := base
	for n := 2; ; n++ {
		if _, err := os.Stat(s.path(id)); errors.Is(err, os.ErrNotExist) {
			return id
		}
		id = fmt.Sprintf("%s-%d", base, n) // two saves in the same second
	}
}

func summarize(g *Graph) Summary {
	return Summary{
		ID:       g.ID,
		Name:     g.Name,
		SavedAt:  g.SavedAt,
		Source:   g.Source,
		Tables:   len(g.Schema.Tables),
		Findings: len(g.Schema.Findings),
	}
}

// writeFileAtomic writes to a temporary file and renames it into place, so
// a crash or a full disk never leaves a half-written graph behind.
func writeFileAtomic(path string, data []byte) error {
	tmp, err := os.CreateTemp(filepath.Dir(path), ".saving-*")
	if err != nil {
		return err
	}
	defer os.Remove(tmp.Name()) // no-op once renamed

	if err := tmp.Chmod(0o600); err != nil {
		tmp.Close()
		return err
	}
	if _, err := tmp.Write(data); err != nil {
		tmp.Close()
		return err
	}
	if err := tmp.Close(); err != nil {
		return err
	}
	return os.Rename(tmp.Name(), path)
}
