package postgres

import (
	"cmp"
	"context"
	"fmt"
	"slices"
	"strings"
	"time"

	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgxpool"

	"github.com/sanat-19/schema-lens/internal/schema"
)

// Introspector reads a Postgres database into a schema.Schema.
type Introspector struct {
	pool    *pgxpool.Pool
	schemas []string // empty means every non-system schema
}

var _ schema.Introspector = (*Introspector)(nil)

// NewIntrospector reads the given schemas, or every non-system schema if
// none are given.
func NewIntrospector(pool *pgxpool.Pool, schemas []string) *Introspector {
	return &Introspector{pool: pool, schemas: schemas}
}

// Introspect reads tables, columns, keys and indexes.
//
// Everything runs inside one read-only REPEATABLE READ transaction, so all
// queries see the catalog at the same moment. Without it, a migration that
// lands halfway through could leave us with an FK pointing at a table we
// didn't see.
func (in *Introspector) Introspect(ctx context.Context) (*schema.Schema, error) {
	tx, err := in.pool.BeginTx(ctx, pgx.TxOptions{
		IsoLevel:   pgx.RepeatableRead,
		AccessMode: pgx.ReadOnly,
	})
	if err != nil {
		return nil, fmt.Errorf("starting read-only transaction: %w", err)
	}
	defer tx.Rollback(ctx) // read-only, so there is never anything to commit

	s := &schema.Schema{CapturedAt: time.Now().UTC()}

	if err := tx.QueryRow(ctx, qServerInfo).Scan(&s.Database, &s.ServerVersion); err != nil {
		return nil, fmt.Errorf("reading server info: %w", err)
	}

	s.Schemas = in.schemas
	if len(s.Schemas) == 0 {
		rows, _ := tx.Query(ctx, qDefaultSchemas)
		s.Schemas, err = pgx.CollectRows(rows, pgx.RowTo[string])
		if err != nil {
			return nil, fmt.Errorf("listing schemas: %w", err)
		}
	}

	tables, err := readTables(ctx, tx, s.Schemas)
	if err != nil {
		return nil, fmt.Errorf("reading tables: %w", err)
	}
	if len(tables) > 0 {
		oids := make([]uint32, 0, len(tables))
		for oid := range tables {
			oids = append(oids, oid)
		}
		if err := readColumns(ctx, tx, oids, tables); err != nil {
			return nil, fmt.Errorf("reading columns: %w", err)
		}
		if err := readConstraints(ctx, tx, oids, tables); err != nil {
			return nil, fmt.Errorf("reading constraints: %w", err)
		}
		if err := readIndexes(ctx, tx, oids, tables); err != nil {
			return nil, fmt.Errorf("reading indexes: %w", err)
		}
	}

	for _, t := range tables {
		markColumnFlags(t)
		s.Tables = append(s.Tables, t)
	}
	slices.SortFunc(s.Tables, func(a, b *schema.Table) int {
		return cmp.Or(cmp.Compare(a.Schema, b.Schema), cmp.Compare(a.Name, b.Name))
	})
	return s, nil
}

// readTables returns the tables keyed by oid; later queries use the oids.
func readTables(ctx context.Context, tx pgx.Tx, schemas []string) (map[uint32]*schema.Table, error) {
	rows, err := tx.Query(ctx, qTables, schemas)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	tables := map[uint32]*schema.Table{}
	for rows.Next() {
		var oid uint32
		t := &schema.Table{}
		if err := rows.Scan(&oid, &t.Schema, &t.Name, &t.Partitioned, &t.Comment,
			&t.RowEstimate, &t.TotalBytes); err != nil {
			return nil, err
		}
		tables[oid] = t
	}
	return tables, rows.Err()
}

func readColumns(ctx context.Context, tx pgx.Tx, oids []uint32, tables map[uint32]*schema.Table) error {
	rows, err := tx.Query(ctx, qColumns, oids)
	if err != nil {
		return err
	}
	defer rows.Close()

	for rows.Next() {
		var (
			oid                 uint32
			c                   schema.Column
			identity, generated string
		)
		if err := rows.Scan(&oid, &c.Name, &c.Type, &c.Nullable, &c.Default,
			&identity, &generated, &c.Comment); err != nil {
			return err
		}
		// Identity and generated columns have no plain default; describe
		// them the way you'd write them in CREATE TABLE.
		switch {
		case identity == "a":
			c.Default = "GENERATED ALWAYS AS IDENTITY"
		case identity == "d":
			c.Default = "GENERATED BY DEFAULT AS IDENTITY"
		case generated == "s":
			expr := c.Default
			if !strings.HasPrefix(expr, "(") {
				expr = "(" + expr + ")"
			}
			c.Default = "GENERATED ALWAYS AS " + expr + " STORED"
		}
		t := tables[oid]
		t.Columns = append(t.Columns, &c)
	}
	return rows.Err()
}

func readConstraints(ctx context.Context, tx pgx.Tx, oids []uint32, tables map[uint32]*schema.Table) error {
	rows, err := tx.Query(ctx, qConstraints, oids)
	if err != nil {
		return err
	}
	defer rows.Close()

	for rows.Next() {
		var (
			oid                 uint32
			name, kind          string
			cols, refCols       []string
			refSchema, refTable string
			onDelete, onUpdate  string
		)
		if err := rows.Scan(&oid, &name, &kind, &cols, &refSchema, &refTable,
			&refCols, &onDelete, &onUpdate); err != nil {
			return err
		}
		t := tables[oid]
		switch kind {
		case "p":
			t.PrimaryKey = cols
		case "u":
			t.Uniques = append(t.Uniques, cols)
		case "f":
			t.ForeignKeys = append(t.ForeignKeys, &schema.ForeignKey{
				Name:       name,
				Columns:    cols,
				RefSchema:  refSchema,
				RefTable:   refTable,
				RefColumns: refCols,
				OnDelete:   fkAction(onDelete),
				OnUpdate:   fkAction(onUpdate),
			})
		}
	}
	return rows.Err()
}

// fkAction decodes pg_constraint.confdeltype / confupdtype.
func fkAction(code string) string {
	switch code {
	case "r":
		return "RESTRICT"
	case "c":
		return "CASCADE"
	case "n":
		return "SET NULL"
	case "d":
		return "SET DEFAULT"
	default: // "a"
		return "NO ACTION"
	}
}

func readIndexes(ctx context.Context, tx pgx.Tx, oids []uint32, tables map[uint32]*schema.Table) error {
	rows, err := tx.Query(ctx, qIndexes, oids)
	if err != nil {
		return err
	}
	defer rows.Close()

	for rows.Next() {
		var oid uint32
		ix := &schema.Index{}
		if err := rows.Scan(&oid, &ix.Name, &ix.Method, &ix.Unique, &ix.Primary,
			&ix.Partial, &ix.Predicate, &ix.Definition, &ix.Columns, &ix.Include,
			&ix.Scans, &ix.Bytes); err != nil {
			return err
		}
		t := tables[oid]
		t.Indexes = append(t.Indexes, ix)
	}
	return rows.Err()
}

// markColumnFlags sets IsPK / IsFK / IsUnique on columns, and records unique
// indexes that aren't constraints as Uniques too: a CREATE UNIQUE INDEX
// guarantees uniqueness just as well, and cardinality depends on it.
func markColumnFlags(t *schema.Table) {
	for _, ix := range t.Indexes {
		if !ix.Unique || ix.Primary || ix.Partial || !allColumns(t, ix.Columns) {
			continue
		}
		if !slices.ContainsFunc(t.Uniques, func(u []string) bool { return slices.Equal(u, ix.Columns) }) {
			t.Uniques = append(t.Uniques, ix.Columns)
		}
	}

	for _, name := range t.PrimaryKey {
		if c := t.Column(name); c != nil {
			c.IsPK = true
		}
	}
	for _, fk := range t.ForeignKeys {
		for _, name := range fk.Columns {
			if c := t.Column(name); c != nil {
				c.IsFK = true
			}
		}
	}
	// Only a single-column unique makes that column unique on its own.
	for _, u := range t.Uniques {
		if len(u) == 1 {
			if c := t.Column(u[0]); c != nil {
				c.IsUnique = true
			}
		}
	}
}

// allColumns reports whether every entry is a real column of t, i.e. the
// index has no expression keys.
func allColumns(t *schema.Table, names []string) bool {
	for _, n := range names {
		if t.Column(n) == nil {
			return false
		}
	}
	return true
}
